# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '30 0 * * 5'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  iptv:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Download & generate IPTV playlist
        run: bash ./script/generate_iptv.sh

      - name: Archive
        uses: actions/upload-artifact@v4
        with:
          name: iptv
          path: ./iptv

  publish:
    runs-on: ubuntu-latest
    needs: [iptv]
    steps:
      - uses: actions/checkout@v3

      - name: Download all artifacts
        uses: actions/download-artifact@v3
        with:
          path: ./publish

      - name: Generate index
        run: python ./script/generate_html.py ./publish

      - name: Publish to Pages
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          folder: ./publish
          clean: true
          branch: gh-pages

